server:
  port: 8080
  servlet:
    #Spring Boot, by default, serves content on the root context path (“/”).
    context-path: /demospring

spring:
  application:
    name: demospring
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      dialect: H2
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_spring
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 23-Manila




#ribbon:
#  ServerListRefreshInterval: 1000




