server:
  port: 8080
  servlet:
    #Spring Boot, by default, serves content on the root context path (“/”).
    context-path: /musicbox

spring:
  application:
    name: musicbox
  jpa:
    hibernate:
      ddl-auto: update
      show_sql: true
      dialect: H2
  datasource:
    url: jdbc:postgresql://localhost:5432/demo_spring
    driverClassName: org.postgresql.Driver
    username: postgres
    password: 23-Manila

  # Templates reloading during development
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false

  # Static resources reloading during development
  resources:
    static-locations: file:src/main/resources/static/


#ribbon:
#  ServerListRefreshInterval: 1000




