SET datestyle = DMY;

INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('James', 'Hetfieldd','04-08-1963',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Paul', 'Rodgers','17-12-1949',NULL,'M','English');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Kirk', ' Hammet','18-11-1962',NULL,'M','American');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Mick','Jagger','26-07-1943',NULL,'M','English');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Joey', 'Ramone','19-05-1951','15-04-2001','M','American');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Lars', 'Ulrich','26-12-1963',NULL,'M','Danish');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Cliff', 'Burton','10-02-1962','27-09-1986','M','American');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Simon', 'Kirke','28-07-1949',NULL,'M','English');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Keith', 'Richards','18-12-1943',NULL,'M','English');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Carles','Sabater','21-09-1962','13-02-1999','M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Pep', 'Sala','17-07-1960',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Lluís', 'Gavaldó','15-04-1963',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Joan', 'Reig','16-03-1963',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Falin', 'Cáceres','27-07-1963',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Ana', 'Torroja','28-12-1959',NULL,'F','Spanish');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Nacho', 'Cano','26-02-1963',NULL,'M','Spanish');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('José María', 'Cano','21-02-1959',NULL,'M','Spanish');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('David', 'Muñoz','10-01-1976',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('José', 'Manuel Munoz','13-11-1978',NULL,'M','Catalan');
INSERT INTO MUSICIAN(name, surname, birth, year_death, gender,nationality) VALUES('Dani', 'Martín','19-02-1977',NULL,'M','Spanish');


/* BAND */
INSERT INTO BAND VALUES(1,'Metallica',1981,NULL,'Heavy','US');
INSERT INTO BAND VALUES(2,'The Rolling Stones',1962,NULL,'Rock','England');
INSERT INTO BAND VALUES(3,'Free',1968,1973,'Rock','England');
INSERT INTO BAND VALUES(4,'Bad Company',1973,NULL,'Rock','England');
INSERT INTO BAND VALUES(5,'Ramones',1974,1996,'Punk','US');
INSERT INTO BAND VALUES(6,'Sau',1987,1999,'Rock','Catalonia');
INSERT INTO BAND VALUES(7,'Els Pets',1985,NULL,'Rock','Catalonia');
INSERT INTO BAND VALUES(8,'Mecano',1981,1992,'Pop','Spain');
INSERT INTO BAND VALUES(9,'Estopa',1999,NULL,'Rock','Catalonia');
INSERT INTO BAND VALUES(10,'El canto del loco',1994,2010,'Pop','Spain');

/* MEMBER */
INSERT INTO MEMBER VALUES(1,1,'Vocals');
INSERT INTO MEMBER VALUES(2,3,'Vocals');
INSERT INTO MEMBER VALUES(2,4,'Vocals');
INSERT INTO MEMBER VALUES(3,1,'Guitar');
INSERT INTO MEMBER VALUES(4,2,'Vocals');
INSERT INTO MEMBER VALUES(5,6,'Vocals');
INSERT INTO MEMBER VALUES(6,1,'Drums');
INSERT INTO MEMBER VALUES(7,1,'Bass');
INSERT INTO MEMBER VALUES(8,3,'Drums');
INSERT INTO MEMBER VALUES(9,2,'Guitar');
INSERT INTO MEMBER VALUES(2,4,'Guitar');
INSERT INTO MEMBER VALUES(1,1,'Guitar');
INSERT INTO MEMBER VALUES(11,6,'Vocals');
INSERT INTO MEMBER VALUES(11,6,'Guitar');
INSERT INTO MEMBER VALUES(12,6,'Keyboard');
INSERT INTO MEMBER VALUES(13,7,'Vocals');
INSERT INTO MEMBER VALUES(13,7,'Guitar');
INSERT INTO MEMBER VALUES(14,7,'Vocals');
INSERT INTO MEMBER VALUES(14,7,'Drums');
INSERT INTO MEMBER VALUES(15,7,'Bass');
INSERT INTO MEMBER VALUES(16,8,'Vocals');
INSERT INTO MEMBER VALUES(17,8,'Keyboard');
INSERT INTO MEMBER VALUES(18,8,'Vocals');
INSERT INTO MEMBER VALUES(18,8,'Guitar');
INSERT INTO MEMBER VALUES(19,9,'Vocals');
INSERT INTO MEMBER VALUES(20,9,'Guitar');
INSERT INTO MEMBER VALUES(21,10,'Vocals');

/* ALBUM */
INSERT INTO ALBUM VALUES(1,'Master of Puppets',1986,1);
INSERT INTO ALBUM VALUES(2,'Fire and Water',1970,3);
INSERT INTO ALBUM VALUES(3,'Aftermath',1966,2);
INSERT INTO ALBUM VALUES(4,'Ride the lightning',1984,1);
INSERT INTO ALBUM VALUES(5,'Free',1969,3);
INSERT INTO ALBUM VALUES(6,'Tattoo You',1981,2);
INSERT INTO ALBUM VALUES(7,'Bad Company',1974,4);
INSERT INTO ALBUM VALUES(8,'Quina nit',1990,6);
INSERT INTO ALBUM VALUES(9,'Entre el cielo y el suelo',1986,8);
INSERT INTO ALBUM VALUES(10,'Ramones',1976,5);
INSERT INTO ALBUM VALUES(11,'Animal Boy',1986,5);

/* SONG */
INSERT INTO SONG VALUES(1,'Battery','00:5:12',1);
INSERT INTO SONG VALUES(2,'Master of Puppets','00:8:35',1);
INSERT INTO SONG VALUES(3,'Mr. Big','00:5:55',2);
INSERT INTO SONG VALUES(4,'All Right Now','00:5:32',2);
INSERT INTO SONG VALUES(5,'Paint It Black','00:5:12',3);
INSERT INTO SONG VALUES(6,'It''s Not Easy','00:5:12',3);
INSERT INTO SONG VALUES(7,'Disposable Heroes','00:8:16',1);
INSERT INTO SONG VALUES(8,'Orion','00:5:32',1);
INSERT INTO SONG VALUES(9,'Fire and Water','00:4:02',2);
INSERT INTO SONG VALUES(10,'Songs of Yesterday','00:3:33',5);
INSERT INTO SONG VALUES(11,'Free Me','00:5:24',5);
INSERT INTO SONG VALUES(12,'Broad Daylight','00:3:15',5);
INSERT INTO SONG VALUES(13,'Start Me Up','00:3:31',6);
INSERT INTO SONG VALUES(14,'Hang Fire','00:2:20',6);
INSERT INTO SONG VALUES(15,'Neighbours','00:3:31',6);
INSERT INTO SONG VALUES(16,'Rock Steady','00:3:47',7);
INSERT INTO SONG VALUES(17,'Ready for Love','00:5:03',7);
INSERT INTO SONG VALUES(18,'Boig per tu','00:4:18',8);
INSERT INTO SONG VALUES(19,'Tanca els ulls','00:1:33',8);
INSERT INTO SONG VALUES(20,'Hijo de la luna','00:4:00',9);
INSERT INTO SONG VALUES(21,'Chain Saw','00:1:56',10);
INSERT INTO SONG VALUES(22,'Loudmouth','00:2:14',10);
INSERT INTO SONG VALUES(23,'Havana Affair','00:1:56',10);
INSERT INTO SONG VALUES(24,'Animal Boy','00:1:50',11);
INSERT INTO SONG VALUES(25,'Apeman Hop','00:2:02',11);
INSERT INTO SONG VALUES(26,'Mental Hell','00:2:38',11);
INSERT INTO SONG VALUES(27,'Me cuesta tanto olvidarte','00:2:54',9);

/* COMPOSER */
INSERT INTO COMPOSER VALUES(1,1);
INSERT INTO COMPOSER VALUES(1,2);
INSERT INTO COMPOSER VALUES(3,2);
INSERT INTO COMPOSER VALUES(2,3);
INSERT INTO COMPOSER VALUES(2,4);
INSERT INTO COMPOSER VALUES(4,5);
INSERT INTO COMPOSER VALUES(4,6);
INSERT INTO COMPOSER VALUES(6,1);
INSERT INTO COMPOSER VALUES(6,2);
INSERT INTO COMPOSER VALUES(1,7);
INSERT INTO COMPOSER VALUES(1,8);
INSERT INTO COMPOSER VALUES(3,7);
INSERT INTO COMPOSER VALUES(6,7);
INSERT INTO COMPOSER VALUES(6,8);
INSERT INTO COMPOSER VALUES(7,8);
INSERT INTO COMPOSER VALUES(2,9);
INSERT INTO COMPOSER VALUES(8,3);
INSERT INTO COMPOSER VALUES(2,10);
INSERT INTO COMPOSER VALUES(2,12);
INSERT INTO COMPOSER VALUES(4,13);
INSERT INTO COMPOSER VALUES(4,14);
INSERT INTO COMPOSER VALUES(4,15);
INSERT INTO COMPOSER VALUES(9,13);
INSERT INTO COMPOSER VALUES(9,14);
INSERT INTO COMPOSER VALUES(9,15);
INSERT INTO COMPOSER VALUES(2,16);
INSERT INTO COMPOSER VALUES(2,17);
INSERT INTO COMPOSER VALUES(12,18);
INSERT INTO COMPOSER VALUES(12,19);
INSERT INTO COMPOSER VALUES(18,20);
INSERT INTO COMPOSER VALUES(5,21);
INSERT INTO COMPOSER VALUES(5,22);
INSERT INTO COMPOSER VALUES(5,23);
INSERT INTO COMPOSER VALUES(5,26);
INSERT INTO COMPOSER VALUES(18,27);

